FROM node:22-alpine

# Habilita o pnpm nativamente no corepack
RUN corepack enable pnpm

WORKDIR /app

# Definir ambiente
ENV NODE_ENV=development
ENV HOST=0.0.0.0

EXPOSE 3000

# Executar a instalação de dependências e subir o servidor Next.js
CMD ["sh", "-c", "pnpm install && pnpm dev"]
